name:                ninetynine
version:             0.3.0.0
github:              "chungyc/ninetynine"
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           "Copyright (C) 2021 Yoo Chung"
homepage:            "http://github.com/chungyc/ninetynine"

extra-source-files:
- README.md
- ChangeLog.md
- doc/*

extra-doc-files:
- images/*/*

# Metadata used when publishing your package
synopsis:            Ninety-Nine Haskell Problems
category:            Education

description: |
  Ninety-Nine Haskell Problems.
  These are programming exercises for practice with [Haskell](https://www.haskell.org/).
  .
  See the "Problems" module for the problems.
  To try your hand at solving the problems, replace the aliases in the problem modules with your own implementations.
  .
  Based on the Ninety-Nine Haskell problems on [HaskellWiki](https://wiki.haskell.org/H-99:_Ninety-Nine_Haskell_Problems).
  For more information, see <https://github.com/chungyc/ninetynine>.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array
  - containers
  - deepseq
  - prettyprinter
  - random
  - text

executables:
  generate-support:
    main:                Main.hs
    source-dirs:         app/support
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - filepath
    - process

tests:
  ninetynine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - containers
    - random
    - hspec
    - QuickCheck
    - generic-random
  examples-test:
    main:                Main.hs
    source-dirs:         app/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest

benchmarks:
  ninetynine-bench:
    main:                Benchmarks.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - containers
    - random
    - deepseq
    - criterion
