name:                ninetynine
version:             0.2.0.0
github:              "chungyc/ninetynine"
license:             BSD3
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           "Copyright (C) 2021 Yoo Chung"
homepage:            "http://github.com/chungyc/ninetynine"

extra-source-files:
- README.md
- ChangeLog.md
- doc/*

extra-doc-files:
- src/Problems/P54/images/*

# Metadata used when publishing your package
synopsis:            Ninety-Nine Haskell Problems
category:            Education

description:         Ninety-Nine Haskell Problems.
                     These are programming exercises for practice with [Haskell](https://www.haskell.org/).
                     The problems are listed in the "Problems" module.

                     Based on the Ninety-Nine Haskell problems on [HaskellWiki](https://wiki.haskell.org/H-99:_Ninety-Nine_Haskell_Problems).
                     For more information, see <https://github.com/chungyc/ninetynine>.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - deepseq

executables:
  ninetynine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine

tests:
  ninetynine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - random
    - hspec
    - QuickCheck
    - generic-random
  examples-test:
    main:                Main.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest

benchmarks:
  ninetynine-bench:
    main:                Benchmarks.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - criterion
    - random
