name:                ninetynine
version:             0.1.0.0
github:              "chungyc/ninetynine"
license:             BSD3
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           "2021 Yoo Chung"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Solutions to Ninety-Nine Haskell Problems
category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/chungyc/ninetynine#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ninetynine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine

tests:
  ninetynine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - hspec
    - QuickCheck
