name:                ninetynine
version:             0.2.0.0
github:              "chungyc/ninetynine"
license:             BSD3
author:              "Yoo Chung"
maintainer:          "dev@chungyc.org"
copyright:           "Copyright (C) 2021 Yoo Chung"

extra-source-files:
- README.md
- ChangeLog.md

extra-doc-files:
- src/Problems/P54/images/*

# Metadata used when publishing your package
synopsis:            Ninety-Nine Haskell Problems
category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Ninety-Nine Haskell Problems.
                     They are listed in the "Problems" module.
                     For more information, please see the README at <https://github.com/chungyc/ninetynine#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - deepseq

executables:
  ninetynine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine

tests:
  ninetynine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - hspec
    - QuickCheck
    - generic-random
  examples-test:
    main:                Main.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest

benchmarks:
  ninetynine-bench:
    main:                Benchmarks.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ninetynine
    - criterion
    - random
