name: Lint
permissions: {}

on:
  push:
  schedule:
    - cron: '15 3 3 * *'

jobs:
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/hlint-scan@v1
