name: Lint

on:
  push:
    paths:
      - '**.hs'

jobs:
  status:
    name: Status checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: haskell/actions/hlint-setup@v2

      - name: Lint
        uses: haskell/actions/hlint-run@v2
        with:
          path: '["src/", "test/", "bench/", "app/"]'
          fail-on: warning

  scan:
    name: Code scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/hlint-scan@v0
