on: [push]
name: test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true

      - name: Build dependencies
        run: stack build --test --bench --only-dependencies --no-run-tests --no-run-benchmarks

      - name: Build
        run: stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack build --test --bench --no-run-benchmarks
